site_name: LocalBox Instructions
site_url: /
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections

nav:
  - Home: index.md
  - Task 1: task1.md
  - Task 2: task2.md
  - Task 3: task3.md
  - Task 4: task4.md
  - Task 5: task5.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - def_list
