site_name: AzBenchmark Instructions
site_url: http://127.0.0.1:8000
docs_dir: ../docs

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.footer
  font:
    text: false
    code: false

extra_css:
  - styles/github-like.css

nav:
  - Instructions: index.md
  - Task 1: task1.md
  - Task 2: task2.md
  - Task 3: task3.md
  - Task 4: task4.md
  - Task 5: task5.md

markdown_extensions:
  - admonition
  - codehilite
  - tables
  - def_list

plugins: []