title: Azure Local Benchmark Docs
description: Guidance and task walkthroughs for this repository
baseurl: ""
url: ""
theme: minima
markdown: kramdown
highlighter: rouge

nav:
  - title: Instructions
    url: /
  - title: Task 1
    url: /task1.html
  - title: Task 2
    url: /task2.html
  - title: Task 3
    url: /task3.html
  - title: Task 4
    url: /task4.html
  - title: Task 5
    url: /task5.html

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

footer_content: "&copy; 2025 Azure Local Benchmark."
